apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qy937o61m-go
  janus-idp.io/tekton: qy937o61m-go
  backstage.io/kubernetes-id: qy937o61m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qy937o61m-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
